# This file was generated by GoReleaser. DO NOT EDIT.
cask "devback" do
  name "devback"
  desc "CLI tool for Git repository backups"
  homepage "https://github.com/arumata/devback"
  version "0.10.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devback"

  on_macos do
    on_intel do
      url "https://github.com/arumata/devback/releases/download/v#{version}/devback_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/arumata/devback"
      sha256 "6dd76ff32280e9843ecd1abbc82433c46c99e532a27948079e64dfbd6c80ffe5"
    end
    on_arm do
      url "https://github.com/arumata/devback/releases/download/v#{version}/devback_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/arumata/devback"
      sha256 "f7b39979e050db7a687daeede3a9cd6956e5d65f241478f77ae362b15ad97460"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arumata/devback/releases/download/v#{version}/devback_#{version}_linux_amd64.tar.gz",
        verified: "github.com/arumata/devback"
      sha256 "c1649cf30992657fdd30d64e5f9d575371007c9b9cb6a9d43a6a70489faf001d"
    end
    on_arm do
      url "https://github.com/arumata/devback/releases/download/v#{version}/devback_#{version}_linux_arm64.tar.gz",
        verified: "github.com/arumata/devback"
      sha256 "067c468ef15b42b43ed4813571dd1241d3b516f5f6aa2ffc2121cfa2004633e4"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/devback"]
    end
  end

  # No zap stanza required
end
