# This file was generated by GoReleaser. DO NOT EDIT.
cask "devback" do
  version "0.12.0"

  on_macos do
    on_intel do
      sha256 "f4a5015bc13b648c9e91be5aa070ae249c9e649b142c661cf6b0168b29406a72"
      url "https://github.com/arumata/devback/releases/download/v#{version}/devback_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/arumata/devback"
    end
    on_arm do
      sha256 "56c47ce0ff998dfe36e17f02351e0202d2e32d58ad00c7070181878ae1e7a237"
      url "https://github.com/arumata/devback/releases/download/v#{version}/devback_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/arumata/devback"
    end
  end

  on_linux do
    on_intel do
      sha256 "a1f4f5db8e18361d7e293351688d5dcef59a37877862463505cd2cba5360d724"
      url "https://github.com/arumata/devback/releases/download/v#{version}/devback_#{version}_linux_amd64.tar.gz",
        verified: "github.com/arumata/devback"
    end
    on_arm do
      sha256 "0f6e3166f24deebd72c85128b993b4276456ac65aa17c5e4ff8d0e4c6f400336"
      url "https://github.com/arumata/devback/releases/download/v#{version}/devback_#{version}_linux_arm64.tar.gz",
        verified: "github.com/arumata/devback"
    end
  end

  name "devback"
  desc "CLI tool for Git repository backups"
  homepage "https://github.com/arumata/devback"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devback"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/devback"]
    end
    system_command "#{staged_path}/devback", args: ["init", "--templates-only", "--force"]
  end

  # No zap stanza required

end
