# This file was generated by GoReleaser. DO NOT EDIT.
cask "devback" do
  version "0.11.0"

  on_macos do
    on_intel do
      sha256 "9c1c270052463296bc26d1a5c0491529302072d91527e259ec9158b4f5375697"
      url "https://github.com/arumata/devback/releases/download/v#{version}/devback_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/arumata/devback"
    end
    on_arm do
      sha256 "ec3ebabd1266234d924afe6422a6952fc810f953b35a037f98b9e34ae28a661a"
      url "https://github.com/arumata/devback/releases/download/v#{version}/devback_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/arumata/devback"
    end
  end

  on_linux do
    on_intel do
      sha256 "e36d67f3755687138b3ce8039722da5fe783903c0cc53e75e3309a7431ad6a99"
      url "https://github.com/arumata/devback/releases/download/v#{version}/devback_#{version}_linux_amd64.tar.gz",
        verified: "github.com/arumata/devback"
    end
    on_arm do
      sha256 "c5fef6002e574080a37e765a76e767ab7f364eae9072df697fc9903fe484a9da"
      url "https://github.com/arumata/devback/releases/download/v#{version}/devback_#{version}_linux_arm64.tar.gz",
        verified: "github.com/arumata/devback"
    end
  end

  name "devback"
  desc "CLI tool for Git repository backups"
  homepage "https://github.com/arumata/devback"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devback"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/devback"]
    end
    system_command "#{staged_path}/devback", args: ["init", "--templates-only", "--force"]
  end

  # No zap stanza required

end
